name: Coverage Check

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Python for diff-cover
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install diff-cover
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and test with coverage
        run: |
          mvn clean verify

      - name: Compare coverage on changed lines
        run: |
          diff-cover target/site/jacoco/jacoco.xml --compare-branch=origin/master --fail-under=80
